version: '3'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

    
services:

  prometheus:
    image: prom/prometheus:v2.37.9
    container_name: sde-prometheus
    user: "0"
    ports:
      - 9090:9090
    command: '--config.file=/etc/prometheus/prometheus.yaml'
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - ./volumes/prometheus-data:/prometheus #fore è da mettere 'prometheus-data' al posto di './data'
    restart: unless-stopped
        
  grafana:
    image: grafana/grafana-oss:latest
    container_name: sde-grafana
    ports:
      - 3000:3000
    user: "1000:1000"
    volumes:
      - ./volumes/grafana-data:/var/lib/grafana
    restart: unless-stopped

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: sde-node_exporter
    command: "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave

  web_service:
    build: ./express_app
    image: express_basics_image
    container_name: sde-web_service_container
    ports: 
      - 8181:8181

  low_requests_fake_client:
    build: ./fake_client/low_requests_fake_client
    image: low_requests_fake_client_image
    container_name: sde-low_requests_fake_client_container

  high_requests_fake_client:
    build: ./fake_client/high_requests_fake_client
    image: high_requests_fake_client_image
    container_name: sde-high_requests_fake_client_container
