{
 "title": "Endpoint_metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request counter for /",
   "type": "timeseries",
   "description": "Counts the number of requests made for the service homepage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(homepage_request_counter[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metrics api response time",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{path=\"/metrics\"}[$__rate_interval]) / rate(http_request_duration_seconds_count{path=\"/metrics\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delayed api response time",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{path=\"/delayed\"}[$__rate_interval]) / rate(http_request_duration_seconds_count{path=\"/delayed\"}[$__rate_interval])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hello api response time",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{path=\"/hello\"}[$__rate_interval]) / rate(http_request_duration_seconds_count{path=\"/hello\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}